---
title: 
author:
date: 
output: pdf_document
header-includes: 
    - \usepackage{amsthm}
    - \usepackage{xcolor}
documentclass: article
<!---output: beamer_presentation--->
---





<!--- Below are global settings for knitr. You can override any of them by adding the changes to individual chunks --->

```{r global_options, include=FALSE}
knitr::opts_chunk$set(error=TRUE,        # Keep compiling upon error
                      collapse=TRUE,     # collapse by default
                      echo=TRUE,         # echo code by default
                      comment = "#>",    # change comment character
                      fig.width = 5,     # set figure width
                      out.width = "50%", # set width of displayed images
                      warning=TRUE,      # show R warnings
                      message=FALSE)     # show R messages
```


<!--- Solution Region --->
<style>
#solution {
  background-color: #8FBC8F;
  border-style: solid;
  border-color: blue;
  margin-left: 20px;
  margin-bottom: 15px;
  padding: 5px;
}
</style>



<!---**Wintersemester 2016 |Studiengang Data Science | Hochschule Darmstadt **--->




\theoremstyle{definition}
\newtheorem{auf}{Aufgabe}

\newcommand{\R}{{\sffamily R} }

\begin{centering}
%\vspace{-2 cm}
\Huge
{\bf Übung 4}\\
\Large
Explorative Datenanalyse und Visualisierung\\
\normalsize
Wintersemester 2019\\
S. Döhler, B. Nedic (FBMN, h\_da)\\
\end{centering}


\hrulefill

**Name:**

**Punkte:**

\hrulefill


\setcounter{auf}{12}
\begin{auf}
Verwenden Sie den R-Datensatz {\ttfamily faithful} (dieser Datensatz ist im base package enthalten). Das Merkmal {\ttfamily eruptions} enthält die Länge von Eruptionen (in Minuten) des Old Faithful Geysirs im Yellowstone National Park in Wyoming, USA. Sie sollen die Verteilung der Eruptionen analysieren. Achten Sie bei allen Grafiken darauf, dass sowohl der Titel der Grafik als auch die Beschriftungen der Achsen möglichst aussagekräftig sind. 

\begin{enumerate}
	 \item[(a)] Laden Sie die Daten und erstellen Sie eine five-point summary.
	 \item[(b)] Erstellen Sie einen Box-Plot und interpretieren Sie diesen.
	 \item[(c)] Erstellen Sie einen Stem and leaf-Plot und interpretieren Sie diesen.
	 \item[(d)] Plotten Sie die empirische Verteilungsfunktion. 
	 \item[(e)] Plotten Sie das Histogramm (inklusive eines "rug-plots") und interpretieren Sie dieses. Experimentieren Sie mit verschiedenen Klassenbreiten. Wie müssen Sie die Optionen einstellen, damit das Histogramm als Dichteschätzer geplottet wird? Wie erhält man ein ähnliches Bild wie beim stem and leaf-Plot?
	 \item[(f)] Plotten Sie ein gleitendes Histogramm in das Histogramm mit ein. Experimentieren Sie mit verschiedenen Bandbreiten. Welche Bandbreite liefert ein "gutes" Ergebnis? 
	 \item[(g)] Wiederholen Sie Teil (f) mit dem Gauß- und Epanechnikov-Kernen.
	 \item[(h)] Vergleichen Sie die verschiedenen Methoden. Was haben Sie über die Daten gelernt? Welche Methode(n) würden Sie einem Anwender empfehlen?
	\end{enumerate}
\end{auf}
\paragraph{Lösung} <!---Hier Schreiben Sie--->

Zu (a):


Zu (b):


Zu (c):


Zu (d):


Zu (e):


Zu (f):


Zu (g):


Zu (h):




\paragraph{Anmerkungen/Korrektur} <!---Hier schreibt der Tutor--->

\textcolor{gray}{\hrulefill}

